name: Deploy on server
run-name: ${{ github.actor }} is deploying on server.
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Create release
        run: dotnet publish -c Release -o publish
