name: Deploy on server
run-name: ${{ github.actor }} is deploying on server.
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Create release
        run: dotnet publish TicTacToe/TicTacToe.csproj -c Release -o publish
